### ISSUE TITLE
セットアップ手順のページのダウンロードリンクがない

### ISSUE THREAD

**Issue by ponkotuy** [ponkotuy/myfleet_web#7]
リンクそのものはあるんだけど対象となる文字列がないので表示されないショボい事案
https://twitter.com/tmpr7/status/582842187311771648

**Comment by b-wind** [comment]
鍵垢リンク……

**Comment by ponkotuy** [comment]
あw すまそ

**Comment by ponkotuy** [comment]
> セットアップ手順のページのダウンロードの「以下のリンクのダウンロードから行いましょう。」の周りにリンクが欲しいです

**Comment by ponkotuy** [comment]
既に直してもらってるからPR待ち
